// <auto-generated />
using System;
using HumanResource.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HumanResource.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HumanResource.Models.MucLuong", b =>
                {
                    b.Property<string>("TenMucLuong")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("SoTien")
                        .HasColumnType("real");

                    b.HasKey("TenMucLuong");

                    b.ToTable("MucLuongs");
                });

            modelBuilder.Entity("HumanResource.Models.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoTen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaPhongBan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenMucLuong")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaPhongBan");

                    b.HasIndex("TenMucLuong");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("HumanResource.Models.PhongBan", b =>
                {
                    b.Property<string>("MaPhongBan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNguoiTruong")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NguoiTruongMaNV")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SoLuongNhanVien")
                        .HasColumnType("int");

                    b.Property<string>("TenPhongBan")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhongBan");

                    b.HasIndex("NguoiTruongMaNV");

                    b.ToTable("PhongBans");
                });

            modelBuilder.Entity("HumanResource.Models.NhanVien", b =>
                {
                    b.HasOne("HumanResource.Models.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhongBan");

                    b.HasOne("HumanResource.Models.MucLuong", "MucLuong")
                        .WithMany("NhanViens")
                        .HasForeignKey("TenMucLuong");

                    b.Navigation("MucLuong");

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("HumanResource.Models.PhongBan", b =>
                {
                    b.HasOne("HumanResource.Models.NhanVien", "NguoiTruong")
                        .WithMany()
                        .HasForeignKey("NguoiTruongMaNV");

                    b.Navigation("NguoiTruong");
                });

            modelBuilder.Entity("HumanResource.Models.MucLuong", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("HumanResource.Models.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });
#pragma warning restore 612, 618
        }
    }
}
